---

- name: Upgrade System Packages
  apt: force=yes update_cache=yes upgrade=yes
  register: system_updated

- name: Install System Packages
  when: system_updated | success
  apt: pkg={{ item }} state=present force=yes
  with_items: system_packages
  register: system_packages_installed
  notify: stop memcached

- name: Place memcached config files
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode=0600
  with_items:
    - { src: memcached.conf.j2, dest: /etc/memcached.conf }
  notify: start memcached
